### ISSUE TITLE
Column alias cannot contain a period

### ISSUE THREAD

**Issue by hhudson** [Pretius/apex-nested-reports#13]
Hello,

Awesome plugin. Small issue: I've found that if the column alias contains a period, the values will not display. 

For example, I have a "Details query" of the "Pretius APEX Nested Reports [Plugin-In]" as the following:
```
select 1234 as "average",
1234 as "avg."
from dual;
```
It is my experience that only the 1234 in the "average" column will display.

Best,
Hayden

**Comment by bostrowski** [comment]
@hhudson 
I know its been long time since your message but I just want you to know I'm started on updating my plugins and I have put your issue in "known bugs" section in readme. Thanks.

**Comment by difr** [comment]
Hello, Bartosz! Thank you very much for such very nice plugin.
I think it can be better, if you will use column alias only for display porpose. For all others (html's attrs) better to use internal names (e.g. COL1, COL2, and so on). Coz this issue is not only about periods in column aliases. Its about many non-alphanumeric characters.
Btw, now it works ok with non-latin chars, but anyway, its better to separate column headings to internal and display parts.

**Comment by bostrowski** [comment]
@difr 
yes, in next release report formatting will be as JSON object with the possibility to set

- th/td aligment
- column header
- td HTML formatting

just like it is implemented for popup report in my plugin for LOV items [Pretis APEX Enhanced LOV Item](https://github.com/bostrowski/Pretius-APEX-Enhanced-Lov-Item)
