### ISSUE TITLE
It's doesn't working with apex18, Tried more, No upgrades?

### ISSUE THREAD

**Issue by AmrAbdeen** [Pretius/apex-nested-reports#15]

**Comment by bostrowski** [comment]
@AmrAbdeen 
sorry for late answer. Official release supporting APEX 18.x will be availble before end of 2018. Small fix within JS code makes the plugin compatibile with latest APEX. Just replace method **.size()** with property **length**. The bug with 18.x is because jQuery dropped support method size in favor for property length.
