### ISSUE TITLE
More level (It's a question not an issue)

### ISSUE THREAD

**Issue by bencegal** [Pretius/apex-nested-reports#32]
Hey!

How can i add more level? ( I need 2-3 more branch )
There is only one branch in the example. But the plugin promises to add as much as I want.

 I want to make a 2-3 level nested report. Is it possible?

**Comment by bostrowski** [comment]
@bencegal 
Yes, this is the main feature of the plug-in.

In order to create more levels you have to follow the instructions but for each nested report. It means you have to embed required information in each nested nested report (if it should has the next level):

- span with class name (column name) and column value as span content
- anchor (as triggering element for next nested report)
- dynamic action implementing the next level of nested report bound with triggering element

the only difference is that you have to include these in nested report SQL Query instead of CR or IR.

Have a look at drilldown example from demo page

![image](https://user-images.githubusercontent.com/15342508/91539788-28bb3380-e91a-11ea-8f28-5487a8f65344.png)

This example is handled by 1 dynamic action which performs drill down on emp table.

**Comment by bencegal** [comment]
Thank you for fast reply but unfortunately I don't really understand this example and it's only use one table.

I followed you usage guide and that's actually nice and understandable.
Please could you do a sample code that complements it with one more level (from a third view/table)? 

For example what I want:  

classic report (from "A" table)
                           +  nested report (from "B" table") - up to this point I am okay with your usage guide
                                      ++ nested report (from "C" table) - but at this point what should I add to the dynamic action SQL query?

**Comment by bostrowski** [comment]
@bencegal 
Sorry for the late answer - I'm no longer Pretius employee and I'm doing support for my Pretius plug-ins in free time.

I've prepared example implementation based on emp and dept tables to produce 3 levels (you can have more if you wish)

- 1st level: select * from dept (classic report) - show all departments
- 2nd level: select * from emp where deptno = #DEPTNO# - show employees in department from row
- 3nd level: select * from emp where MGR = #EMPNO# - show inferriors for employee from row

[f20517 (1).zip](https://github.com/Pretius/apex-nested-reports/files/5189258/f20517.1.zip)

Download and install the application at apex.oracle.com. Don't forget to install supporting objects, which will install the plug-in package.

**Comment by bencegal** [comment]
@bostrowski 
I am grateful that you are still dealing with the support.

Thank you for this example, it's so clean and nice, that's what I want! :)

Now I'm understand the method, thanks again!
